const Exception = (message) => {
  console.log(message)
  throw new Error(message)
}
